spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
